# Generated by Django 4.1.4 on 2022-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('programming_language', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('prefered_loc', models.CharField(max_length=100)),
                ('prof_image', models.ImageField(upload_to='')),
                ('project', models.TextField()),
            ],
        ),
    ]
